const productos = [
    { nombre: "Menú del día", precio: 360 },
    { nombre: "Ensalada completa", precio: 360 },
    { nombre: "Ensalada tibia", precio: 360 },
    { nombre: "Ensalada de palta", precio: 360 },
    { nombre: "Ensalada de garbanzos", precio: 360 },
    { nombre: "Empanada", precio: 125 },
    { nombre: "Croqueta", precio: 85 },
    { nombre: "Tarta", precio: 165 },
    { nombre: "Tarta, ensalada, arroz integral", precio: 315 },
    { nombre: "Bocata", precio: 320 },
    { nombre: "Sopa", precio: 180 },
    { nombre: "Brownie", precio: 120 },
    { nombre: "Brownie con helado", precio: 190 },
    { nombre: "Salchichon", precio: 95 },
    { nombre: "Torta del día", precio: 110 },
    { nombre: "Jugo grande", precio: 160 },
    { nombre: "Jugo chico", precio: 100 },
    { nombre: "Agua", precio: 110 },
    { nombre: "Kombucha", precio: 185 },
    { nombre: "Birra artesanal", precio: 230 },
    { nombre: "Coca cola", precio: 110 },
    { nombre: "Café espresso", precio: 95 },
    { nombre: "Café americano", precio: 120 },
    { nombre: "Café cortado", precio: 135 },

];